# Generated by Django 5.0.1 on 2024-01-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_useraccount_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
