# Generated by Django 5.0.1 on 2024-03-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cashtransferinsura_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargotransportinsur',
            name='tripType',
            field=models.CharField(choices=[('Land', 'Land'), ('Sea', 'Sea'), ('Air', 'Air')], default='Land', max_length=60),
        ),
        migrations.AddField(
            model_name='cashsafekeepinsura',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=60),
        ),
        migrations.AddField(
            model_name='fireinsur',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Check', 'Check')], default='Cash', max_length=60),
        ),
        migrations.AddField(
            model_name='honestyguaranteeinsur',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=60),
        ),
        migrations.AddField(
            model_name='transportationinsur',
            name='contractCurr',
            field=models.CharField(choices=[('Dollar', 'Dollar'), ('IQ', 'IQ')], default='IQ', max_length=60),
        ),
        migrations.AddField(
            model_name='transportationinsur',
            name='tripType',
            field=models.CharField(choices=[('Land', 'Land'), ('Sea', 'Sea'), ('Air', 'Air')], default='Land', max_length=60),
        ),
    ]
